ProjectTemp/Areas/Admin/Controllers/CatagoryController.cs
using BookLelo.DataAccess.Data;
using BookLelo.Model;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace BookLelo.Areas.Admin.Controllers
{
    public class CatagoryController : Controller
    {
        private readonly ApplicationDbContext _Context;

        public CatagoryController(ApplicationDbContext context)
        {
            _Context = context;
        }

        // GET: CatagoryController
        public IActionResult Index()
        {
            IEnumerable<Catagory> CatagoryList = _Context.Catagories.ToList();
            return View(CatagoryList);
        }

        // GET: CatagoryController/Details/5
        public IActionResult Details(int id)
        {
            return View();
        }

        // GET: CatagoryController/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CatagoryController/Create
        [HttpPost]
        public IActionResult Create(Catagory catagory)
        {
            if (catagory.Name == catagory.DisplayOrder.ToString())
            {
                ModelState.AddModelError("Error", "Name And Dispaly Order Cannot Be Same");
            }
            _Context.Catagories.Add(catagory);
            _Context.SaveChanges();
            TempData["Success"] = "Catagory Added SuccessFully";
            return RedirectToAction("Index");
        }

        // GET: CatagoryController/Edit/5
        public IActionResult Edit(int id)
        {
            if (id == null && id == 0)
                return NotFound();
            var data = _Context.Catagories.Find(id);
            if (data == null)
                return View(data);
            return View(data);
        }

        // POST: CatagoryController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Catagory catagory)
        {
            if (catagory.Name == catagory.DisplayOrder.ToString())
            {
                ModelState.AddModelError("Error", "Name And Dispaly Order Cannot Be Same");
            }
            _Context.Catagories.Update(catagory);
            _Context.SaveChanges();
            TempData["Success"] = "Catagory Updated SuccessFully";
            return RedirectToAction("Index");
        }

        // GET: CatagoryController/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null && id == 0)
            {
                return NotFound();
            }
            var catagoryFromDb = _Context.Catagories.Find(id);
            if (catagoryFromDb == null)
            {
                NotFound();
            }
            return View(catagoryFromDb);
        }

        // POST: CatagoryController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _Context.Catagories.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            _Context.Catagories.Remove(obj);
            _Context.SaveChanges();
            TempData["Success"] = "Catagory Deleted SuccessFully";
            return RedirectToAction("Index");
        }
    }
}

ProjectTemp/Areas/Admin/Controllers/CoverTypeController.cs
using BookLelo.DataAccess.Data;
using BookLelo.Model;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace BookLelo.Areas.Admin.Controllers
{
    public class CoverTypeController : Controller
    {
        private readonly ApplicationDbContext _Context;

        public CoverTypeController(ApplicationDbContext context)
        {
            _Context = context;
        }

        // GET: CatagoryController
        public IActionResult Index()
        {
            IEnumerable<CoverType> CoverTypeList = _Context.CoverType.ToList();
            return View(CoverTypeList);
        }

        // GET: CatagoryController/Details/5
        public IActionResult Details(int id)
        {
            return View();
        }

        // GET: CatagoryController/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CatagoryController/Create
        [HttpPost]
        public IActionResult Create(CoverType CoverType)
        {

            _Context.CoverType.Add(CoverType);
            _Context.SaveChanges();
            TempData["Success"] = "Catagory Added SuccessFully";
            return RedirectToAction("Index");
        }

        // GET: CatagoryController/Edit/5
        public IActionResult Edit(int id)
        {
            if (id == null && id == 0)
                return NotFound();
            var data = _Context.CoverType.Find(id);
            if (data == null)
                return View(data);
            return View(data);
        }

        // POST: CatagoryController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CoverType CoverType)
        {

            _Context.CoverType.Update(CoverType);
            _Context.SaveChanges();
            TempData["Success"] = "Catagory Updated SuccessFully";
            return RedirectToAction("Index");
        }

        // GET: CatagoryController/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null && id == 0)
            {
                return NotFound();
            }
            var CoverTypeFromDb = _Context.CoverType.Find(id);
            if (CoverTypeFromDb == null)
            {
                NotFound();
            }
            return View(CoverTypeFromDb);
        }

        // POST: CatagoryController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _Context.CoverType.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            _Context.CoverType.Remove(obj);
            _Context.SaveChanges();
            TempData["Success"] = "Catagory Deleted SuccessFully";
            return RedirectToAction("Index");
        }
    }
}

ProjectTemp/Areas/Customer/Controllers/HomeController.cs
using BookLelo.Model;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ProjectTemp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProjectTemp/Areas/Admin/Views/Catagory/Create.cshtml
@model Catagory

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Create Catagory</h2>
            <hr />
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="DisplayOrder"></label>
            <input asp-for="DisplayOrder" class="form-control" />
            <span asp-validation-for="DisplayOrder" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
        <a asp-controller="catagory" asp-action="index" class="btn btn-secondary" style="width:150px">Back To List</a>
    </div>
</form>

ProjectTemp/Areas/Admin/Views/Catagory/Delete.cshtml
@model Catagory

<form method="post" asp-action="Delete">
	<input asp-for="Id" hidden />
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Delete Category</h2>
			<hr />
		</div>
		@*<div asp-validation-summary="All"></div>*@
		<div class="mb-3">
			<label asp-for="Name"></label>
			<input asp-for="Name" disabled class="form-control" />
		</div>
		<div class="mb-3">
			<label asp-for="DisplayOrder"></label>
			<input asp-for="DisplayOrder" disabled class="form-control" />
		</div>
		<button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
		<a asp-controller="Catagory" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back to List
		</a>
    </div>
</form>

ProjectTemp/Areas/Admin/Views/Catagory/Edit.cshtml
@model Catagory

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit Catagory</h2>
            <hr />
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="DisplayOrder"></label>
            <input asp-for="DisplayOrder" class="form-control" />
            <span asp-validation-for="DisplayOrder" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
        <a asp-controller="catagory" asp-action="index" class="btn btn-secondary" style="width:150px">Back To List</a>
    </div>
</form>

ProjectTemp/Areas/Admin/Views/Catagory/Index.cshtml
@model IEnumerable<Catagory>

  
   <Partial name="_notification" />
    <div class="container p-3">
        <div class="row pt-4">
            <div class="col-6">
                <h2 class="text-primary">Catagory List</h2>
            </div>
            <div class="col-6 text-end">
            <a asp-controller="Catagory" asp-action="Create" class="btn btn-primary"><i class="bi bi-plus-circle"></i>Create New Catagory</a>
            </div>
        </div>
    </div>

<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <td>Catagory Name</td>
            <td>Display Order</td>
            <td>Action</td>
        </tr>
    </thead>
    <tbody>
        @foreach (var data in Model)
        {
            <tr>
                <td width="50%">@data.Name</td>
                <td width="30%">@data.DisplayOrder</td>
                <td><a asp-action="Edit" asp-controller="Catagory" class="btn btn-success" asp-route-Id="@data.Id">Edit</a></td>
                <td><a asp-action="Delete" asp-controller="Catagory" class="btn btn-danger" asp-route-Id="@data.Id">Delete</a></td>
            </tr>
        }
    </tbody>
</table>

ProjectTemp/Areas/Admin/Views/CoverType/Create.cshtml
@model CoverType

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Create Catagory</h2>
            <hr />
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="type"></label>
            <input asp-for="type" class="form-control"/>
            <span asp-validation-for="type" class="text-danger"></span>
        </div>
        
        <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
        <a asp-controller="CoverType" asp-action="Index" class="btn btn-secondary" style="width:150px">Back To List</a>
    </div>
</form>

ProjectTemp/Areas/Admin/Views/CoverType/Delete.cshtml
@model CoverType

<form method="post" asp-action="Delete">
	<input asp-for="Id" hidden />
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Delete Category</h2>
			<hr />
		</div>
		@*<div asp-validation-summary="All"></div>*@
		<div class="mb-3">
			<label asp-for="type"></label>
			<input asp-for="type" disabled class="form-control" />
		</div>
		
		<button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
		<a asp-controller="CoverType" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back to List
		</a>
    </div>
</form>

ProjectTemp/Areas/Admin/Views/CoverType/Edit.cshtml
@model CoverType

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit Catagory</h2>
            <hr />
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="type"></label>
            <input asp-for="type" class="form-control"/>
            <span asp-validation-for="type" class="text-danger"></span>
        </div>
        
        <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
        <a asp-controller="CoverType" asp-action="index" class="btn btn-secondary" style="width:150px">Back To List</a>
    </div>
</form>

ProjectTemp/Areas/Admin/Views/CoverType/Index.cshtml
@model IEnumerable<CoverType>

  
   <Partial name="_notification" />
    <div class="container p-3">
        <div class="row pt-4">
            <div class="col-6">
            <h2 class="text-primary">CoverType List</h2>
            </div>
            <div class="col-6 text-end">
            <a asp-controller="Covertype" asp-action="Create" class="btn btn-primary"><i class="bi bi-plus-circle"></i>Create New Covertype</a>
            </div>
        </div>
    </div>

<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <td>Covertype</td>
          
            <td>Action</td>
        </tr>
    </thead>
    <tbody>
        @foreach (var data in Model)
        {
            <tr>
                <td width="50%">@data.type</td>
                <td><a asp-action="Edit" asp-controller="CoverType" class="btn btn-success" asp-route-Id="@data.Id">Edit</a></td>
                <td><a asp-action="Delete" asp-controller="CoverType" class="btn btn-danger" asp-route-Id="@data.Id">Delete</a></td>
            </tr>
        }
    </tbody>
</table>

ProjectTemp/Areas/Customer/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ProjectTemp/Areas/Customer/Views/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjectTemp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjectTemp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProjectTemp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Catagory" asp-action="Index">Catagory</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="CoverType" asp-action="Index">Covertype</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ProjectTemp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ProjectTemp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjectTemp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjectTemp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProjectTemp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Catagory" asp-action="Index">Catagory</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="CoverType" asp-action="Index">Covertype</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ProjectTemp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ProjectTemp/Views/Shared/_notification.cshtml
 <script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
@if(TempData["success"]!=null){
<script>
    toastr.success('@TempData["success"]');
</script>
    }  
@if(TempData["error"]!=null){
    <script>
        toastr.success('@TempData["error"]');
    </script>
    }